export const AutoSportNewsGroup = {
	image:        'autosport.gif',
	title:        'Autosport',
	description:  'Autosport News Feed',
	group:        'sport',
	category:     'USA',
	path:         '/sport/autosport',
	country:      'USA',
	website:      'https://www.autosport.com/',
	youtube:      'https://www.youtube.com/user/AUTOSPORTdotcom',
	facebook:     'https://www.facebook.com/autosport/',
  twitter:      'https://twitter.com/autosport',
	rss:          'https://www.autosport.com/rss',
}

export const AutoSportNewsFeeds = [
	{
		title: 'Categories',
		feeds: [
			{
				label: 'All news',
				title: 'Autosport - All news RSS Feed',
				path: '/sport/autosport/all-news',
				url: 'https://www.autosport.com/rss/feed/all',
			},
			{
				label: 'Features',
				title: 'Autosport - Features RSS Feed',
				path: '/sport/autosport/features',
				url: 'https://www.autosport.com/rss/feed/features',
			},
			{
				label: 'Formula 1',
				title: 'Autosport - Formula 1 RSS Feed',
				path: '/sport/autosport/',
				url: 'https://www.autosport.com/rss/feed/f1',
			},
			{
				label: 'British Touring Car Championship',
				title: 'Autosport - British Touring Car Championship RSS Feed',
				path: '/sport/autosport/',
				url: 'https://www.autosport.com/rss/feed/btcc',
			},
			{
				label: 'World Rally Championship',
				title: 'Autosport - World Rally Championship RSS Feed',
				path: '/sport/autosport/',
				url: 'https://www.autosport.com/rss/feed/wrc',
			},
			{
				label: 'WNASCAR',
				title: 'Autosport - NASCAR RSS Feed',
				path: '/sport/autosport/nascar',
				url: 'https://www.autosport.com/rss/feed/nascar',
			},
			{
				label: 'F2',
				title: 'Autosport - F2 RSS Feed',
				path: '/sport/autosport/f2',
				url: 'https://www.autosport.com/rss/feed/f2',
			},
			{
				label: 'Formula 3',
				title: 'Autosport - Formula 3 RSS Feed',
				path: '/sport/autosport/formula-3',
				url: 'https://www.autosport.com/rss/feed/f3',
			},
			{
				label: 'Other',
				title: 'Autosport - Other RSS Feed',
				path: '/sport/autosport/other',
				url: 'https://www.autosport.com/rss/feed/other',
			},
			{
				label: 'Historics',
				title: 'Autosport - Historics RSS Feed',
				path: '/sport/autosport/historics',
				url: 'https://www.autosport.com/rss/feed/historics',
			},
			{
				label: 'Autosport Awards',
				title: 'Autosport - Autosport Awards RSS Feed',
				path: '/sport/autosport/autosport-awards',
				url: 'https://www.autosport.com/rss/feed/awards',
			},
			{
				label: 'Autosport Magazine',
				title: 'Autosport - Autosport Magazine RSS Feed',
				path: '/sport/autosport/autosport-magazine',
				url: 'https://www.autosport.com/rss/feed/mag',
			},
			{
				label: 'Autosport Performance',
				title: 'Autosport Performance RSS Feed',
				path: '/sport/autosport/autosport-magazine',
				url: 'https://www.autosport.com/rss/feed/performance',
			},
			{
				label: 'Autosport Engineering',
				title: 'Autosport Engineering RSS Feed',
				path: '/sport/autosport/autosport-engineering',
				url: 'https://www.autosport.com/rss/feed/engineering',
			},
			{
				label: 'Esports',
				title: 'Esports RSS Feed',
				path: '/sport/autosport/esports',
				url: 'https://www.autosport.com/rss/feed/esports',
			},
			{
				label: 'Reviews',
				title: 'Reviews RSS Feed',
				path: '/sport/autosport/reviews',
				url: 'https://www.autosport.com/rss/feed/reviews',
			},
			{
				label: 'Autosport Show',
				title: 'Autosport Show RSS Feed',
				path: '/sport/autosport/autosport-show',
				url: 'https://www.autosport.com/rss/feed/asi',
			},
			{
				label: 'Autosport.com',
				title: 'Autosport.com RSS Feed',
				path: '/sport/autosport/autosport-show',
				url: 'https://www.autosport.com/rss/feed/national',
			},
			{
				label: 'National',
				title: 'National RSS Feed',
				path: '/sport/autosport/national',
				url: 'https://www.autosport.com/rss/feed/national',
			},
			{
				label: 'World Endurance Championship',
				title: 'World Endurance Championship RSS Feed',
				path: '/sport/autosport/world-endurance-championship',
				url: 'https://www.autosport.com/rss/feed/wec',
			},
			{
				label: 'DTM',
				title: 'DTM RSS Feed',
				path: '/sport/autosport/dtm',
				url: 'https://www.autosport.com/rss/feed/dtm',
			},
			{
				label: 'IndyCar',
				title: 'IndyCar RSS Feed',
				path: '/sport/autosport/indycar',
				url: 'https://www.autosport.com/rss/feed/indycar',
			},
			{
				label: 'GT',
				title: 'GT RSS Feed',
				path: '/sport/autosport/gt',
				url: 'https://www.autosport.com/rss/feed/gt',
			},
			{
				label: 'World Touring Car Cup',
				title: 'World Touring Car Cup RSS Feed',
				path: '/sport/autosport/gt',
				url: 'https://www.autosport.com/rss/feed/wtcr',
			},
			{
				label: 'FV8 3.5',
				title: 'FV8 3.5RSS Feed',
				path: '/sport/autosport/fv-835',
				url: '',
			},
			{
				label: 'Supercars',
				title: 'Supercars RSS Feed',
				path: '/sport/autosport/fv-835',
				url: 'https://www.autosport.com/rss/feed/sup',
			},
			{
				label: 'European Rally Championship',
				title: 'European Rally Championship RSS Feed',
				path: '/sport/autosport/european-rally-championship',
				url: 'https://www.autosport.com/rss/feed/erc',
			},
			{
				label: 'GP3',
				title: 'GP3 RSS Feed',
				path: '/sport/autosport/gp3',
				url: 'https://www.autosport.com/rss/feed/gp3',
			},
			{
				label: 'Auto GP',
				title: 'Auto GP RSS Feed',
				path: '/sport/autosport/auto-gp',
				url: 'https://www.autosport.com/rss/feed/autogp',
			},
			{
				label: 'Indy Lights',
				title: 'Indy Lights RSS Feed',
				path: '/sport/autosport/indy-lights',
				url: 'https://www.autosport.com/rss/feed/lights',
			},
			{
				label: 'World Rallycross',
				title: 'World Rallycross RSS Feed',
				path: '/sport/autosport/world-rallycross',
				url: 'https://www.autosport.com/rss/feed/wrx',
			},
			{
				label: 'IMSA SportsCar',
				title: 'IMSA SportsCar RSS Feed',
				path: '/sport/autosport/imsa-sportscar',
				url: 'https://www.autosport.com/rss/feed/imsa',
			},
			{
				label: 'Formula E',
				title: 'Formula E RSS Feed',
				path: '/sport/autosport/formula-e',
				url: 'https://www.autosport.com/rss/feed/fe',
			},
			{
				label: 'Dakar',
				title: 'Dakar RSS Feed',
				path: '/sport/autosport/dakar',
				url: 'https://www.autosport.com/rss/feed/dakar',
			},
			{
				label: 'MotoGP',
				title: 'MotoGP RSS Feed',
				path: '/sport/autosport/motogp',
				url: 'https://www.autosport.com/rss/feed/motogp',
			},
			{
				label: 'Moto2',
				title: 'Moto2 RSS Feed',
				path: '/sport/autosport/moto2',
				url: 'https://www.autosport.com/rss/feed/moto2',
			},
			{
				label: 'Moto3',
				title: 'Moto3 RSS Feed',
				path: '/sport/autosport/moto3',
				url: 'https://www.autosport.com/rss/feed/moto3',
			},
			{
				label: 'TT',
				title: 'TT RSS Feed',
				path: '/sport/autosport/tt',
				url: 'https://www.autosport.com/rss/feed/tt',
			},
			{
				label: 'Motorsport Leaders Business Forum',
				title: 'Motorsport Leaders Business Forum RSS Feed',
				path: '/sport/autosport/motorsport-leaders-busness-forum',
				url: 'https://www.autosport.com/rss/feed/leaders',
			},
			{
				label: 'Motor1',
				title: 'Motor1 RSS Feed',
				path: '/sport/autosport/motor1',
				url: 'https://www.autosport.com/rss/feed/m1',
			},
			{
				label: 'Motorsport Network',
				title: 'Motorsport Network RSS Feed',
				path: '/sport/autosport/motorsport-network',
				url: 'https://www.autosport.com/rss/feed/netw',
			},
			{
				label: 'Rallying',
				title: 'Rallying RSS Feed',
				path: '/sport/autosport/rallying',
				url: 'https://www.autosport.com/rss/feed/rallying',
			},
			{
				label: 'U.S.',
				title: 'U.S. RSS Feed',
				path: '/sport/autosport/rallying',
				url: 'https://www.autosport.com/rss/feed/us',
			},
			{
				label: 'Motorsport',
				title: 'Motorsport RSS Feed',
				path: '/sport/autosport/rallying',
				url: 'https://www.autosport.com/rss/feed/motorsport',
			},
			{
				label: 'Single-seaters',
				title: 'Single-seaters RSS Feed',
				path: '/sport/autosport/single-seaters',
				url: 'https://www.autosport.com/rss/feed/single-seaters',
			},
			{
				label: 'Single-seaters',
				title: 'Single-seaters RSS Feed',
				path: '/sport/autosport/single-seaters',
				url: 'https://www.autosport.com/rss/feed/touring+cars',
			},
			{
				label: 'Touring Cars',
				title: 'Touring Cars RSS Feed',
				path: '/sport/autosport/touring-cars',
				url: '',
			},
			{
				label: 'Sportscars',
				title: 'Sportscars RSS Feed',
				path: '/sport/autosport/sportscars',
				url: 'https://www.autosport.com/rss/feed/sportscars',
			},
			{
				label: 'Bikes',
				title: 'Bikes RSS Feed',
				path: '/sport/autosport/bikes',
				url: 'https://www.autosport.com/rss/feed/bikes',
			},
		]
	}
];
