export const RaiTelevideoNewsGroup = {
  image:        'ansa.gif',
	title:        'Televideo Rai',
	description:  'Latest news on Televideo RAI',
	group:        'news',
	category:     'Italy',
	path:         '/news/rai-televideo',
	country:      'Italy',
	website:      'http://www.servizitelevideo.rai.it/',
	youtube:      '',
	facebook:     '',
  twitter:      '',
  gplus:        '',
	wikipedia:    '',
	rss:          'http://www.servizitelevideo.rai.it/televideo/pub/rsslista.jsp',
};

export const RaiTelevideoNewsFeeds = [
	{
		title: 'Categories',
		feeds: [
      {
				label: 'Ultim\'Ora ',
				title: 'Ultim\'Ora Televideo Rai RSS feeds',
				path: '/news/rai-televideo/ultim-ora',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss101.xml',
			},
      {
				label: '24h no stop',
				title: '24h no stop Televideo Rai RSS feeds',
				path: '/news/rai-televideo/ultim-ora',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss102.xml',
			},
      {
				label: 'Primopiano',
				title: 'Primopiano Televideo Rai RSS feeds',
				path: '/news/rai-televideo/primopiano',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss110.xml',
			},
      {
				label: 'Politica',
				title: 'Politica Televideo Rai RSS feeds',
				path: '/news/rai-televideo/politica',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss120.xml',
			},
      {
				label: 'Economia',
				title: 'Economia Televideo Rai RSS feeds',
				path: '/news/rai-televideo/economia',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss130.xml',
			},
      {
				label: 'Dall\'Italia',
				title: 'Dall\'Italia Televideo Rai RSS feeds',
				path: '/news/rai-televideo/dall-italia',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss140.xml',
			},
      {
				label: 'Dal Mondo',
				title: 'Dal Mondo Televideo Rai RSS feeds',
				path: '/news/rai-televideo/dal-mondo',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss150.xml',
			},
      {
				label: 'Culture',
				title: 'Culture Televideo Rai RSS feeds',
				path: '/news/rai-televideo/culture',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss160.xml',
			},
      {
				label: 'Cittadini',
				title: 'Cittadini Televideo Rai RSS feeds',
				path: '/news/rai-televideo/cittadini',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss170.xml',
			},
      {
				label: 'Speciale',
				title: 'Speciale Televideo Rai RSS feeds',
				path: '/news/rai-televideo/speciale',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss180.xml',
			},
      {
				label: 'Atlante delle Crisi',
				title: 'Atlante delle Crisi Televideo Rai RSS feeds',
				path: '/news/rai-televideo/atlante-delle-crisi',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss190.xml',
			},
      {
				label: 'Calcio',
				title: 'Calcio Televideo Rai RSS feeds',
				path: '/news/rai-televideo/calcio',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss201.xml',
			},
      {
				label: 'Brevi Calcio',
				title: 'Brevi Calcio Televideo Rai RSS feeds',
				path: '/news/rai-televideo/brevi-calcio',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss229.xml',
			},
      {
				label: 'Calcio Squadre',
				title: 'Calcio Squadre Televideo Rai RSS feeds',
				path: '/news/rai-televideo/calcio-squadre',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss230.xml',
			},
      {
				label: 'Altri Sport',
				title: 'Altri Sport Televideo Rai RSS feeds',
				path: '/news/rai-televideo/altri-sport',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss260.xml',
			},
      {
				label: 'Brevissime',
				title: 'Brevissime Televideo Rai RSS feeds',
				path: '/news/rai-televideo/brevissime',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss299.xml',
			},
      {
				label: 'Telesoftware',
				title: 'Telesoftware Televideo Rai RSS feeds',
				path: '/news/rai-televideo/telesoftware',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss790.xml',
			},
      {
				label: 'Motori',
				title: 'Motori Televideo Rai RSS feeds',
				path: '/news/rai-televideo/motori',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rss810.xml',
			},
      {
				label: 'Articoli web',
				title: 'Articoli web Televideo Rai RSS feeds',
				path: '/news/rai-televideo/articoli-web',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rssarticoli.xml',
			},
      {
				label: 'Home page',
				title: 'Home page web Televideo Rai RSS feeds',
				path: '/news/rai-televideo/home-page',
				url: 'http://www.servizitelevideo.rai.it/televideo/pub/rsshp.xml',
			},
    ],
  },
];